import { at, BEATS, heartbeatFrames, isNotificationThought, SCENES, thoughtSpawnFrame, VIDEO, VO, VoiceLineId } from "./timing";

// ─────────────────────────────────────────────────────────────────────────────
// SOUND DESIGN MAP
// All effects are synthesized by remotion/scripts/generate-sfx.mjs
// (`npm run remotion:sfx`) into remotion/public/audio/sfx/. No samples, no
// paid assets. To swap a sound, drop another file in remotion/public/audio/
// and change its `src` (path relative to remotion/public). `src: null` mutes
// a cue. SoundLayer.tsx places every cue and fades everything out at the end.
// ─────────────────────────────────────────────────────────────────────────────

export type SoundCue = {
  id: string;
  from: number; // absolute frame (30 fps)
  // Cue is cut off after this many frames (used for the hard cuts).
  durationInFrames?: number;
  src: string | null;
  volume: number;
  note: string;
};

// ▶ VOICEOVER — one file per line in remotion/public/audio/vo/<id>.wav,
// generated by `npm run remotion:voiceover` (Syrian neural voice, see
// voiceover.json). Each line plays from VO[id].start in timing.ts — the same
// frame its caption appears. To use a human recording instead, replace the
// WAV files (same names) and re-run the script's manifest step, or point
// `dir` to another folder with the same file names.
export const VOICEOVER = {
  enabled: true,
  dir: "audio/vo",
  volume: 1,
};

export const VOICE_CUES = (Object.keys(VO) as VoiceLineId[]).map((id) => ({
  id,
  from: VO[id].start,
  src: `${VOICEOVER.dir}/${id}.wav`,
}));

const sfx = (name: string) => `audio/sfx/${name}.wav`;

// Length of each generated file, in frames.
const LENGTH = {
  heartbeat: 21,
  notification: 21,
  reverseSuck: 21,
  whoosh: 27,
  glitch: 9,
} as const;

// The two hard cuts: at 0:01.5 the thoughts vanish, at the hard stop (≈0:08.7) everything stops.
const HOOK_CUT = at("hook", BEATS.hook.thoughtsEnd);
const HARD_STOP = SCENES.turn.from;

// Length that makes a cue stop exactly on `cut` (if it would ring past it).
const until = (from: number, length: number, cut: number) =>
  from < cut ? Math.max(1, Math.min(length, cut - from)) : length;

const NOTIFICATION_VARIANTS = ["notification-a", "notification-b", "notification-c"];

export const SOUND_CUES: SoundCue[] = [
  // 0:00–0:01.5 · HEARTBEAT — one "lub-dub" per beat, accelerating with the
  // thoughts (76 → 156 bpm) and cut dead at 0:01.5. Two single thumps land on
  // the hook headlines; a softer 104 bpm pulse runs under the problem scene.
  ...heartbeatFrames().map((frame, i) => {
    const inHook = frame < HOOK_CUT;
    return {
      id: `heartbeat-${i}`,
      from: frame,
      durationInFrames: until(frame, LENGTH.heartbeat, inHook ? HOOK_CUT : HARD_STOP),
      src: sfx("heartbeat"),
      // The thumps under the headlines sit lower so they don't clip with the impact.
      volume: inHook ? 1 : frame < SCENES.problem.from ? 0.5 : 0.4,
      note: "heartbeat one-shot (low, muffled, felt more than heard)",
    };
  }),

  // 0:00–0:01.5 · NOTIFICATIONS — a soft ping on every thought drawn as a
  // phone notification, getting a little louder as the panic builds.
  ...Array.from({ length: BEATS.hook.thoughtCount }, (_, i) => i)
    .filter(isNotificationThought)
    .map((i, k) => {
      const frame = thoughtSpawnFrame(i, BEATS.hook.thoughtCount, BEATS.hook.thoughtSpawnWindow);
      return {
        id: `notification-${k}`,
        from: frame,
        durationInFrames: until(frame, LENGTH.notification, HOOK_CUT),
        src: sfx(NOTIFICATION_VARIANTS[k % NOTIFICATION_VARIANTS.length]),
        volume: 0.22 + k * 0.05,
        note: "notification ping, three pitches",
      };
    }),

  // 0:00.8–0:01.5 · HARD CUT — reverse-cymbal suck that ends exactly on the
  // frame the thoughts vanish. After it: silence.
  {
    id: "cut-to-silence",
    from: HOOK_CUT - LENGTH.reverseSuck,
    durationInFrames: LENGTH.reverseSuck,
    src: sfx("reverse-suck"),
    volume: 0.85,
    note: "reverse-cymbal suck ending exactly on the cut",
  },
  // 0:01.5 · "القلق عنده خدعة."
  { id: "impact-trick", from: at("hook", BEATS.hook.trick), src: sfx("impact"), volume: 0.6, note: "deep sub impact" },
  // ≈0:03.5 · "بيطلب منك تحل بكرا… اليوم." — tonal hits on بكرا and اليوم
  // Word 4 (بكرا) and word 5 (اليوم) pop 2 frames after they start revealing.
  { id: "hit-bukra", from: at("hook", BEATS.hook.demand + 3 * BEATS.hook.demandStagger + 2), src: sfx("hit-high"), volume: 0.35, note: "tonal hit on بكرا" },
  { id: "hit-alyom", from: at("hook", BEATS.hook.demand + 4 * BEATS.hook.demandStagger + 2), src: sfx("hit-low"), volume: 0.45, note: "tonal hit on اليوم" },
  // ≈0:04.4 · WHOOSH into the mental timeline (peaks on the scene change)
  { id: "whoosh-timeline", from: at("hook", BEATS.hook.exit), src: sfx("whoosh"), volume: 0.55, note: "fast whoosh / air rush" },
  // 0:04.6–0:08.7 · timeline rushing past
  {
    id: "timeline-drone",
    from: SCENES.problem.from,
    durationInFrames: HARD_STOP - SCENES.problem.from,
    src: sfx("drone"),
    volume: 0.28,
    note: "rising tense drone, slowly getting louder",
  },
  // the loader keeps spinning
  {
    id: "loader-ticking",
    from: at("problem", BEATS.problem.loader),
    durationInFrames: HARD_STOP - at("problem", BEATS.problem.loader),
    src: sfx("ticking"),
    volume: 0.15,
    note: "dry clock ticking, speeding up",
  },
  // ≈0:07.0 / 0:07.5 / 0:08.0 · flashes "مضمون؟" "أكيد؟" "شو بعدين؟"
  ...BEATS.problem.flashes.map((beat, i) => ({
    id: `flash-${i}`,
    from: at("problem", beat),
    durationInFrames: LENGTH.glitch,
    src: sfx("glitch"),
    volume: 0.28,
    note: "short glitch tick",
  })),
  // 0:08.7 · HARD STOP — everything above is cut on this frame; the drone's
  // pitch collapses (tape-stop), then ~1 s of true silence.
  { id: "hard-stop", from: HARD_STOP, src: sfx("tape-stop"), volume: 0.45, note: "tape-stop, then silence" },
  // 0:09.7 → end · CALM AMBIENCE — warm pad in D; brightens as the solution starts.
  {
    id: "calm-ambience",
    from: HARD_STOP + 30,
    durationInFrames: VIDEO.durationInFrames - HARD_STOP - 30,
    src: sfx("ambience"),
    volume: 0.28,
    note: "calm ambient pad, 2 s fade-in, warmer as the solution starts",
  },
  // ≈0:15.3 · the task gets checked off
  { id: "check", from: at("solution", BEATS.solution.check), src: sfx("check"), volume: 0.4, note: "soft, warm UI tick" },
  // ≈0:17.5–0:19.4 · the knot loosens
  {
    id: "knot-release",
    from: at("solution", BEATS.solution.letGo + BEATS.solution.knotLoosen[0]),
    src: sfx("release"),
    volume: 0.35,
    note: "string tension releasing / long exhale",
  },
  // ≈0:19.8 · soft whoosh landing on a single piano note with "اليوم."
  {
    id: "whoosh-today",
    from: at("solution", BEATS.solution.backToToday + BEATS.solution.today - 6),
    src: sfx("today"),
    volume: 0.5,
    note: "soft slow whoosh + single piano note (D4)",
  },
  // ≈0:23.5 · the next step lights up
  { id: "step-light", from: at("payoff", BEATS.payoff.stepLight), src: sfx("shimmer"), volume: 0.35, note: "warm shimmer / light swell" },
  // ≈0:27.2 · "وبكرا… منستقبله بكرا."
  { id: "final-swell", from: at("final", BEATS.final.line2), src: sfx("resolve"), volume: 0.45, note: "gentle resolving D major chord" },
  // ≈0:29.5 → 0:30 · everything fades out with the picture (SoundLayer).
];

// Master fade-out, in sync with the picture's FadeToBlack.
export const MASTER_FADE = {
  from: at("final", BEATS.final.fadeOut),
  to: VIDEO.durationInFrames - 1,
} as const;
