import { at, BEATS, heartbeatFrames, isNotificationThought, SCENES, thoughtSpawnFrame, VIDEO, VO, VoiceLineId } from "./timing";

// ─────────────────────────────────────────────────────────────────────────────
// SOUND DESIGN MAP
// All effects are synthesized by remotion/scripts/generate-sfx.mjs
// (`npm run remotion:sfx`) into remotion/public/audio/sfx/. No samples, no
// paid assets. To swap a sound, drop another file in remotion/public/audio/
// and change its `src` (path relative to remotion/public). `src: null` mutes
// a cue. SoundLayer.tsx places every cue and fades everything out at the end.
// ─────────────────────────────────────────────────────────────────────────────

export type SoundCue = {
  id: string;
  from: number; // absolute frame (30 fps)
  // Cue is cut off after this many frames (used for the hard cuts).
  durationInFrames?: number;
  // Skip this many frames at the start of the file.
  trimBefore?: number;
  src: string | null;
  volume: number;
  note: string;
};

// ▶ VOICEOVER — one file per line in remotion/public/audio/vo/<id>.wav,
// generated by `npm run remotion:voiceover` (Syrian neural voice, see
// voiceover.json). Each line plays from VO[id].start in timing.ts — the same
// frame its caption appears. To use a human recording instead, replace the
// WAV files (same names) and re-run the script's manifest step, or point
// `dir` to another folder with the same file names.
export const VOICEOVER = {
  enabled: true,
  dir: "audio/vo",
  volume: 1,
};

export const VOICE_CUES = (Object.keys(VO) as VoiceLineId[]).map((id) => ({
  id,
  from: VO[id].start,
  src: `${VOICEOVER.dir}/${id}.wav`,
}));

const sfx = (name: string) => `audio/sfx/${name}.wav`;

// Length of each generated file, in frames (see generate-sfx.mjs).
const LENGTH = {
  heartbeat: 21,
  notification: 21,
  reverseSuck: 21,
  whoosh: 27,
  glitch: 9,
  drone: 420,
  ticking: 300,
  riser: 150,
} as const;

// The two hard cuts: the thoughts vanish (≈0:02), and the hard stop where
// everything stops (≈0:15). Both follow timing.ts.
const HOOK_CUT = at("hook", BEATS.hook.thoughtsEnd);
const HARD_STOP = SCENES.turn.from;

// Length that makes a cue stop exactly on `cut` (if it would ring past it).
const until = (from: number, length: number, cut: number) =>
  from < cut ? Math.max(1, Math.min(length, cut - from)) : length;

const NOTIFICATION_VARIANTS = ["notification-a", "notification-b", "notification-c"];
const LOADER_FROM = at("problem", BEATS.problem.loader);

export const SOUND_CUES: SoundCue[] = [
  // HEARTBEAT — one "lub-dub" per beat, accelerating with the thoughts
  // (70 → 160 bpm) and cut dead when they vanish. Two single thumps land on
  // the hook headlines; a softer pulse accelerates again under the problem.
  ...heartbeatFrames().map((frame, i) => {
    const inHook = frame < HOOK_CUT;
    return {
      id: `heartbeat-${i}`,
      from: frame,
      durationInFrames: until(frame, LENGTH.heartbeat, inHook ? HOOK_CUT : HARD_STOP),
      src: sfx("heartbeat"),
      // The thumps under the headlines sit lower so they don't clip with the impact.
      volume: inHook ? 1 : frame < SCENES.problem.from ? 0.5 : 0.4,
      note: "heartbeat one-shot (low, muffled, felt more than heard)",
    };
  }),

  // NOTIFICATIONS — a soft ping on every thought drawn as a phone
  // notification, getting a little louder as the panic builds.
  ...Array.from({ length: BEATS.hook.thoughtCount }, (_, i) => i)
    .filter(isNotificationThought)
    .map((i, k) => {
      const frame = thoughtSpawnFrame(i, BEATS.hook.thoughtCount, BEATS.hook.thoughtSpawnWindow);
      return {
        id: `notification-${k}`,
        from: frame,
        durationInFrames: until(frame, LENGTH.notification, HOOK_CUT),
        src: sfx(NOTIFICATION_VARIANTS[k % NOTIFICATION_VARIANTS.length]),
        volume: 0.22 + k * 0.05,
        note: "notification ping, three pitches",
      };
    }),

  // HARD CUT — reverse-cymbal suck that ends exactly on the frame the
  // thoughts vanish. After it: silence.
  {
    id: "cut-to-silence",
    from: HOOK_CUT - LENGTH.reverseSuck,
    durationInFrames: LENGTH.reverseSuck,
    src: sfx("reverse-suck"),
    volume: 0.85,
    note: "reverse-cymbal suck ending exactly on the cut",
  },
  // "للقلق خدعةٌ واحدة." (with the white flash frame)
  { id: "impact-trick", from: BEATS.hook.trick, src: sfx("impact"), volume: 0.6, note: "deep sub impact" },
  // "يطلب منك أن تحلّ الغد… اليوم." — word 5 (الغد) and word 6 (اليوم) pop
  // 2 frames after they start revealing.
  { id: "hit-ghad", from: BEATS.hook.demand + 4 * BEATS.hook.demandStagger + 2, src: sfx("hit-high"), volume: 0.35, note: "tonal hit on الغد" },
  { id: "hit-alyom", from: BEATS.hook.demand + 5 * BEATS.hook.demandStagger + 2, src: sfx("hit-low"), volume: 0.45, note: "tonal hit on اليوم" },
  // WHOOSH into the mental timeline (peaks on the scene change + flash)
  { id: "whoosh-timeline", from: at("hook", BEATS.hook.exit), src: sfx("whoosh"), volume: 0.55, note: "fast whoosh / air rush" },
  // The timeline rushing past: the drone is trimmed at its start so its
  // loudest part always ends exactly on the hard stop.
  {
    id: "timeline-drone",
    from: SCENES.problem.from,
    durationInFrames: HARD_STOP - SCENES.problem.from,
    trimBefore: Math.max(0, LENGTH.drone - (HARD_STOP - SCENES.problem.from)),
    src: sfx("drone"),
    volume: 0.28,
    note: "rising tense drone, slowly getting louder",
  },
  // The loader keeps spinning: ticking speeds up towards the hard stop.
  {
    id: "loader-ticking",
    from: LOADER_FROM,
    durationInFrames: HARD_STOP - LOADER_FROM,
    trimBefore: Math.max(0, LENGTH.ticking - (HARD_STOP - LOADER_FROM)),
    src: sfx("ticking"),
    volume: 0.15,
    note: "dry clock ticking, speeding up",
  },
  // Flashes "مضمون؟" "أكيد؟" "ثم ماذا؟"
  ...BEATS.problem.flashes.map((beat, i) => ({
    id: `flash-${i}`,
    from: at("problem", beat),
    durationInFrames: LENGTH.glitch,
    src: sfx("glitch"),
    volume: 0.28,
    note: "short glitch tick",
  })),
  // "وكلّما بحثتَ أكثر… ازداد الضجيج." — a riser that peaks on the hard stop.
  {
    id: "riser",
    from: HARD_STOP - LENGTH.riser,
    durationInFrames: LENGTH.riser,
    src: sfx("riser"),
    volume: 0.4,
    note: "noise + pitch riser, loudest on its last frame, then cut",
  },
  // HARD STOP — everything above is cut on this frame; the drone's pitch
  // collapses (tape-stop), then ~1.3 s of true silence.
  { id: "hard-stop", from: HARD_STOP, src: sfx("tape-stop"), volume: 0.45, note: "tape-stop, then silence" },
  // "لكن… توقّف لحظة." — one deep, soft boom on "توقّف".
  {
    id: "stop-boom",
    from: VO.stop.start + Math.round(VO.stop.frames * 0.35),
    src: sfx("sub-boom"),
    volume: 0.6,
    note: "soft, deep sub boom",
  },
  // CALM AMBIENCE — warm pad in D; fades in with "توقّف", brightens as the solution starts.
  {
    id: "calm-ambience",
    from: HARD_STOP + 30,
    durationInFrames: VIDEO.durationInFrames - HARD_STOP - 30,
    src: sfx("ambience"),
    volume: 0.28,
    note: "calm ambient pad, 2 s fade-in, warmer as the solution starts",
  },
  // The task gets checked off.
  { id: "check", from: at("solution", BEATS.solution.doIt + BEATS.solution.check), src: sfx("check"), volume: 0.4, note: "soft, warm UI tick" },
  // The knot loosens.
  {
    id: "knot-release",
    from: at("solution", BEATS.solution.letGo + BEATS.solution.knotLoosen[0]),
    src: sfx("release"),
    volume: 0.35,
    note: "string tension releasing / long exhale",
  },
  // Soft whoosh landing on a single piano note with "اليوم."
  {
    id: "whoosh-today",
    from: at("solution", BEATS.solution.backToToday + BEATS.solution.today - 6),
    src: sfx("today"),
    volume: 0.5,
    note: "soft slow whoosh + single piano note (D4)",
  },
  // The next step lights up.
  { id: "step-light", from: at("payoff", BEATS.payoff.stepLight), src: sfx("shimmer"), volume: 0.35, note: "warm shimmer / light swell" },
  // "والغد… نستقبله غدًا."
  { id: "final-swell", from: at("final", BEATS.final.line2), src: sfx("resolve"), volume: 0.45, note: "gentle resolving D major chord" },
  // Everything fades out with the picture (SoundLayer).
];

// Master fade-out, in sync with the picture's FadeToBlack.
export const MASTER_FADE = {
  from: at("final", BEATS.final.fadeOut),
  to: VIDEO.durationInFrames - 1,
} as const;
